In [2]:
# this notebook loads each movie's frames into the X_input matrix

# boilerplate
import cv2
import numpy as np
import os
from data_utils_local08 import *

In [4]:
# determine the number of frames in the longest movie
# also figure out the max width and height of each frame
num_movies = 7
num_frames = 0
max_width = 0
max_height = 0

for num in range(num_movies):
    if (7 + num) < 10:
        path = os.path.join("data_movies/MEDIAEVAL18_0{}.mp4".format(7 + num))
    else:
        path = os.path.join("data_movies/MEDIAEVAL18_{}.mp4".format(7 + num))
    vidcap = cv2.VideoCapture(path)
    
    mov_frames = int(vidcap.get(cv2.CAP_PROP_FRAME_COUNT))
    frm_width = int(vidcap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frm_height = int(vidcap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    if (mov_frames > num_frames):
        num_frames = mov_frames
    if (frm_width > max_width):
        max_width = frm_width
    if (frm_height > max_height):
        max_height = frm_height
        
print(num_frames)
print(max_width)
print(max_height)

6298
640
360


In [ ]:
# now for creating the data matrix

# let's start testing small
num_movies = 7

# the master matrix
X_input = np.zeros([num_movies, num_frames,  max_height, max_width, 3])


# for each movie
for num in range(num_movies):
    if (7 + num) < 10:
        path = os.path.join("data_movies/MEDIAEVAL18_0{}.mp4".format(7 + num))
    else:
        path = os.path.join("data_movies/MEDIAEVAL18_{}.mp4".format(7 + num))
    vidcap = cv2.VideoCapture(path) 

    success, image = vidcap.read()
    # count may need to be started outside of the loop that runs through all of the videos
    count = 0
    while success:
        # add the image to the X_input_test array
        X_input[num, count, :, :, :] = image[:, :, :]
        # read the next image from video file
        success, image = vidcap.read()
        count = count + 1

print(count)
#print(X_input)

In [17]:
print(X_input[3][2005])

[[59. 54. 46.]
 [63. 57. 52.]
 [64. 59. 51.]
 ...
 [23. 26. 26.]
 [27. 30. 30.]
 [28. 31. 31.]]


In [18]:
# overwrite the existing .npy file
np.save('./pixel_data_full', X_input)