In [ ]:
# this notebook loads each movie's frames into the X_input matrix

# boilerplate
import cv2
import numpy as np
import os
from data_utils_local08 import *

In [ ]:
# determine the number of frames in the longest movie
num_movies = 7
num_frames = 0

for num in range(num_movies):
    if (7 + num) < 10:
        path = os.path.join("data_movies/MEDIAEVAL18_0{}.mp4".format(7 + num))
    else:
        path = os.path.join("data_movies/MEDIAEVAL18_{}.mp4".format(7 + num))
    vidcap = cv2.VideoCapture(path)
    mov_frames = int(vidcap.get(cv2.CAP_PROP_FRAME_COUNT))
    if (mov_frames > num_frames):
        num_frames = mov_frames
        
print(num_frames)

In [14]:
# now for creating the data matrix

# dimensions autoencoder requires
new_width = 64
new_height = 64

# let's start testing small
num_movies = 7

# the master matrix
X_input = np.zeros([num_movies, num_frames, new_width*new_height, 3])


# for each movie
for num in range(num_movies):
    if (7 + num) < 10:
        path = os.path.join("data_movies/MEDIAEVAL18_0{}.mp4".format(7 + num))
    else:
        path = os.path.join("data_movies/MEDIAEVAL18_{}.mp4".format(7 + num))
    vidcap = cv2.VideoCapture(path)
    
    width = int(vidcap.get(cv2.CAP_PROP_FRAME_WIDTH)) # same for all movies i think
    height = int(vidcap.get(cv2.CAP_PROP_FRAME_HEIGHT)) # same for all movies i think

    success, image = vidcap.read()
    # count may need to be started outside of the loop that runs through all of the videos
    count = 0
    while success:
        # flatten the image --> reshape it 
        img = downsize_forAuto(image)
        new_img = np.reshape(img, [new_width*new_height, 3])
        # add the image to the X_input_test array
        X_input[num, count, :, :] = new_img[:, :]
        # read the next image from video file
        success, image = vidcap.read()
        count = count + 1

print(count)
#print(X_input)

6298


In [17]:
print(X_input[3][2005])

[[59. 54. 46.]
 [63. 57. 52.]
 [64. 59. 51.]
 ...
 [23. 26. 26.]
 [27. 30. 30.]
 [28. 31. 31.]]


In [18]:
# overwrite the existing .npy file
np.save('./train_data_Auto01', X_input)