In [6]:
# the goal here is to create matrices out of all the visual feature data
import cv2
import numpy as np
import os, math, csv
from data_utils_local09 import *

In [8]:
# this is for loading the audio features

import csv
with open('/Users/chloeloughridge/Desktop/AI Grant Project/Dataset/2018 Task Data/audio_features/MEDIAEVAL18_07/MEDIAEVAL18_07_00007.csv', 'rt') as csvfile:
    csvreader = csv.reader(csvfile, delimiter=' ')
    for row in csvreader:
        #if np.asarray(row)[0] == 'noname':
        #if row.split()[0] == 'noname':
        #print(row.strip().split(','))
        for word in row:
            if word.split(',')[0] == "'noname'":
                #print(word.split(',')[0])
                num_data = word
                print(num_data)

'noname',6.252546e-01,3.380855e-01,7.379503e-01,3.397167e-04,6.547197e-01,1.977287e-01,6.354149e-02,2.566321e-01,5.942783e-01,3.115931e+00,5.464195e-01,7.066610e-01,8.789369e-01,1.602415e-01,1.722758e-01,3.325174e-01,2.819028e-01,1.364591e+00,1.082688e+00,2.240326e-02,4.073320e-03,7.291242e-01,6.109979e-03,5.661675e-01,2.185740e-02,-4.788896e+00,4.223037e+00,3.080637e+01,6.356437e+00,-1.257378e+00,5.329487e+00,-1.705173e+00,1.511045e+00,4.621174e+00,3.216218e+00,3.110129e+00,6.326348e+00,-1.988938e+01,1.168076e+01,3.157014e+01,3.625255e-01,5.295316e-02,6.191446e-01,7.352342e-01,-1.180824e+01,-3.010229e-03,-1.107073e+01,5.204641e+00,4.028192e+01,6.361129e+00,-2.456988e-02,2.648228e+00,-1.660906e+01,-1.134157e+01,-7.156793e+00,5.267497e+00,4.184772e+00,9.452269e+00,-2.591183e+01,3.320352e+00,2.923218e+01,6.720977e-02,2.036660e-02,1.364562e-01,4.134420e-01,-6.736087e+00,-4.116731e-02,3.349904e+00,8.121527e+00,9.345924e+01,1.129189e+01,4.903641e-01,2.455373e+00,-1.539739e+01,-8.312245e+00,

In [9]:
# for loading audio features

num_data_array = np.asarray(num_data.split(","))
print(num_data_array.shape)
string_data = num_data_array[1:]
print(string_data)
int_data_array = np.asarray(string_data, dtype=np.float32)
print(int_data_array)


(1584,)
['6.252546e-01' '3.380855e-01' '7.379503e-01' ... '9.000000e+00'
 '4.930000e+00' '0.0']
[0.6252546 0.3380855 0.7379503 ... 9.        4.93      0.       ]


In [7]:
# GATHERING THE AUDIO FEATURE DATA
# create a master array of shape [7,207,1584]
audio_data = np.zeros([12, 6262, 1583])

# for each of the movies in the set of 12
for num in range(12):
    mov = num + 54
    # for each of the files in the audio data folder
    if mov < 10:
        path = os.path.join('/Users/chloeloughridge/Desktop/MEDIAEVAL18-TestSet-Audio_features/audio_features/MEDIAEVAL18_0{}'.format(mov))
    else:
        path = os.path.join('/Users/chloeloughridge/Desktop/MEDIAEVAL18-TestSet-Audio_features/audio_features/MEDIAEVAL18_{}'.format(mov))
    count = 0
    for file in os.listdir(path):
        filename = os.fsdecode(file)
        if filename.endswith(".csv"):
            # read the second's worth of data into numpy array
            with open(os.path.join(path, filename), 'rt') as csvfile:
                csvreader = csv.reader(csvfile, delimiter=' ')
                for row in csvreader:
                    for word in row:
                        if word.split(',')[0] == "'noname'":
                            #print(word.split(',')[0])
                            num_data = word
                            num_data_array = np.asarray(num_data.split(","))
                            string_data = num_data_array[1:]
                            int_data_array = np.asarray(string_data, dtype=np.float32)
                            # slot this numpy array into the appropriate spot in the master array
                            audio_data[num, count, :] = int_data_array
            #print(count)
            count = count + 1
    print(mov)
# print out the master array
print(audio_data)

54
55
56
57
58
59
60
61
62
63
64
65
[[[ 0.8313008   0.          0.84720451 ... 47.          4.94000006
    0.        ]
  [ 0.8313008   0.          0.84720451 ... 47.          4.94000006
    0.        ]
  [ 0.8313008   0.          0.84720451 ... 47.          4.94000006
    0.        ]
  ...
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]]

 [[ 0.93292677  0.          0.52076459 ... 47.          4.94000006
    0.        ]
  [ 0.93292677  0.          0.52076459 ... 47.          4.94000006
    0.        ]
  [ 0.93292677  0.          0.52076459 ... 47.          4.94000006
    0.        ]
  ...
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]]



In [8]:
np.save('../Desktop/audio_test.npy', audio_data)

In [25]:
audio_data[:7, :207, :] = np.load('../Desktop/audio_feature_data.npy')[:8, :, :]
print(audio_data)

[[[ 0.93292677  0.          0.55344039 ... 42.          4.94000006
    0.        ]
  [ 0.93292677  0.          0.55344039 ... 42.          4.94000006
    0.        ]
  [ 0.93292677  0.          0.55344039 ... 42.          4.94000006
    0.        ]
  ...
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]]

 [[ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  ...
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]]

 [[ 0.          0.          0.         ...  0.          0.
 

In [29]:
for i in audio_data[13][5]:
    if i != 0:
        print("yass!")

yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass!
yass

In [22]:
np.save('../Desktop/audio_data01.npy', audio_data)

In [3]:
# find some key variables, like the max number of seconds in each movie

VGG_data_dim = 4096
num_movies=7
# find the movie with the longest number of seconds
# set timesteps to zero
timesteps = 0
# iterate through all of the movies and compute num_secs/timesteps for each
# for each movie
for num in range(num_movies):
    if (7 + num) < 10:
        path = os.path.join("data_movies/MEDIAEVAL18_0{}.mp4".format(7 + num))
    else:
        path = os.path.join("data_movies/MEDIAEVAL18_{}.mp4".format(7 + num))
    vidcap = cv2.VideoCapture(path)
    # calculate the number of seconds
    frame_rate = math.floor(vidcap.get(cv2.CAP_PROP_FPS))
    # get total number of frames in the movie
    num_frames = vidcap.get(cv2.CAP_PROP_FRAME_COUNT)
    # get the number of seconds in the movie by dividing by frames per second 
    curr_timesteps = round(num_frames/frame_rate)
    # if the current timestep value is greater than timesteps
    if curr_timesteps > timesteps:
        # set timesteps to the curr_timestep value
        timesteps = curr_timesteps



In [6]:
# will start by creating the labels matrix for the 7 movies
labels_matrix = np.zeros([num_movies, timesteps])

# for each movie number between and including 7 and 13
for num in range(num_movies):
    # create the appropriate path to the fear annotation data
    #print(num)
    if num+7 < 10:
        path = os.path.join('/Users/chloeloughridge/Desktop/AI Grant Project/Dataset/2018 Task Data/MEDIAEVAL18-DevSet-Part1-Fear-annotations/annotations/MEDIAEVAL18_0{}_Fear.txt'.format(7+num))
    if num+7 > 10:
        path = os.path.join('/Users/chloeloughridge/Desktop/AI Grant Project/Dataset/2018 Task Data/MEDIAEVAL18-DevSet-Part1-Fear-annotations/annotations/MEDIAEVAL18_{}_Fear.txt'.format(7+num))
    # create a one-hot vector
    y_data = fear_oneHot(timesteps, path)
    # add this one-hot vector to y_train_data
    labels_matrix[num, :] = y_data
    
print(labels_matrix[4])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0.]


In [7]:
np.save('../Desktop/labels02', labels_matrix)

In [4]:
# NOW LOADING VGG DATA ARRAY
VGG_data_dim = 4096
timesteps=212
VGG16_feature_data = np.zeros([num_movies, timesteps, VGG_data_dim])

# for each movie
for num in range(num_movies):
    # load the X_input data
    X_input = load_Xinput(get_fc6_directory(7 + num))
    # put this X_input data into the X_train_data array
    VGG16_feature_data[num, :, :] = X_input

In [16]:
# LOADING VGG DATA FROM TEST SET
VGG_data_dim = 4096
timesteps=5564
num_movies = 12
VGG16_test_data = np.zeros([num_movies, timesteps, VGG_data_dim])

# for each movie
for num in range(num_movies):
    # load the X_input data
    # get the file path
    mov = 54 + num
    path = os.path.join('/Users/chloeloughridge/Desktop/MEDIAEVAL18-TestSet-Visual_features/visual_features/MEDIAEVAL18_{}/fc6'.format(mov))
    count = 0
    for file in os.listdir(path):
        filename = os.fsdecode(file)
        if filename.endswith(".txt"):
            input_data = np.loadtxt(os.path.join(path, file), delimiter=',')
            VGG16_test_data[num, count, :] = np.asarray(input_data)[:]
            #print(os.path.join(directory, filename))
            #print(count)
            count = count + 1
            continue
        else:
            continue
    print(num)
            
print(count)
print(VGG16_test_data.shape)
print(VGG16_test_data)

0
1
2
3
4
5
6
7
8
9
10
11
5564
(12, 5564, 4096)
[[[ -4.4444    0.76968  -3.2783  ...   0.23307  -1.0833   -0.45209]
  [ -4.5598    0.79331  -3.3777  ...   0.30708  -1.0658   -0.51627]
  [ -6.067    -8.4672   -6.7512  ... -10.636    -9.7449    4.7505 ]
  ...
  [  0.        0.        0.      ...   0.        0.        0.     ]
  [  0.        0.        0.      ...   0.        0.        0.     ]
  [  0.        0.        0.      ...   0.        0.        0.     ]]

 [[ -4.8072    1.0747   -3.548   ...   0.33026  -1.3472   -0.25087]
  [ -4.9485    0.96946  -3.4589  ...   0.12901  -1.2983   -0.19144]
  [ -6.1164   -8.6679   -7.4226  ... -10.407   -10.222     4.948  ]
  ...
  [  0.        0.        0.      ...   0.        0.        0.     ]
  [  0.        0.        0.      ...   0.        0.        0.     ]
  [  0.        0.        0.      ...   0.        0.        0.     ]]

 [[ -4.7292    0.2542   -2.9289  ...   0.52958  -1.3883   -0.68409]
  [ -4.736     0.26421  -2.905   ...   0.4996   -1.3

In [17]:
np.save('../Desktop/VGG16_test_data', VGG16_test_data)

In [56]:
# getting the data_dim of the specified feature data 
# currently you have to manually plug in the feature name
# COULD BE A DATA UTILS FUNCTION
fname='lbp'
feature = np.loadtxt('/Users/chloeloughridge/Desktop/AI Grant Project/Dataset/2018 Task Data/MEDIAEVAL18-DevSet-Part1-Visual_features/visual_features/MEDIAEVAL18_07/{}/MEDIAEVAL18_07-00001_{}.txt'.format(fname, fname), dtype=np.unicode)
feature_list = feature.tolist()
data_dim = len(feature_list.split(","))
print(data_dim)

256


In [ ]:
# AUDIO DATA LOADING
timesteps = 212
num_movies=7
fname='lbp'
feature = np.loadtxt('/Users/chloeloughridge/Desktop/AI Grant Project/Dataset/2018 Task Data/MEDIAEVAL18-DevSet-Part1-Audio_features/audio_features/MEDIAEVAL18_07/{}/MEDIAEVAL18_07-00001_{}.txt'.format(fname, fname), dtype=np.unicode)
feature_list = feature.tolist()
data_dim = len(feature_list.split(","))
print(data_dim)

In [57]:
# AUDIO DATA LOADING CONTINUED

lbp_feature_data = np.zeros([num_movies, timesteps, data_dim])

# for each movie
for num in range(num_movies):
    # load the X_input data
    X_input = load_audioXinput(get_feature_directory(fname, 7 + num), timesteps, data_dim)
    # put this X_input data into the X_train_data array
    lbp_feature_data[num, :, :] = X_input


In [58]:
print(tamura_feature_data)

[[[3.65885417e+00 3.29260240e+00 2.22000000e+02 ... 1.62000000e+02
   1.69000000e+02 1.52000000e+02]
  [3.65885417e+00 3.29604464e+00 2.18000000e+02 ... 1.64000000e+02
   1.57000000e+02 1.60000000e+02]
  [3.51649306e+00 5.96096926e+00 1.99000000e+02 ... 1.57000000e+02
   1.78000000e+02 1.75000000e+02]
  ...
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]]

 [[3.65885417e+00 3.29211434e+00 2.10000000e+02 ... 1.55000000e+02
   1.73000000e+02 1.55000000e+02]
  [3.65885417e+00 3.30292873e+00 2.18000000e+02 ... 1.70000000e+02
   1.55000000e+02 1.52000000e+02]
  [3.51822917e+00 5.96566482e+00 2.31000000e+02 ... 1.72000000e+02
   1.79000000e+02 1.52000000e+02]
  ...
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000

In [59]:
np.save('LBP_feature_data', lbp_feature_data)

In [60]:
!mv LBP_feature_data.npy ../Desktop