In [1]:
# normalized VGG16 feature data fed into simple LSTM

# First, import necessary libraries
import tensorflow as tf
import numpy as np
import keras.backend as K

/Users/chloeloughridge/anaconda/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
Using TensorFlow backend.


In [2]:
# setting up the keras stuff
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten, BatchNormalization
from keras.layers import LSTM
# my custom data_utils file
from data_utils_local08 import *

In [21]:
# uploading the X values
#X_input = np.load('../Desktop/Cloud_Training/data/VGG16_data01.npy')[7:, :212, :] #VGG16 data

X_input = np.load('../Desktop/VGG16_feature_data.npy')

#X_input = np.load('VGG16.npy')
# X_input = np.load('../Desktop/InceptionResNetV2_feature_data.npy') #resnet data!



#X_input = np.load('../Desktop/audio_feature_data.npy') #audio feature data!

print(X_input.shape)

(7, 212, 4096)


In [31]:
X_input2 = np.load('../Desktop/Cloud_Training/data/VGG16_data01.npy')[7:, :212, :]
if X_input2.all() == X_input.all():
    print('yey')

yey


In [22]:
# uploading the Y values
#y_data_input = np.load('../Desktop/Cloud_Training/data/labels01.npy')[7:, :212]
y_data_input = np.load('../Desktop/labels.npy')
#y_data_input = np.load('labels.npy')
balance = np.mean(y_data_input)
print(balance)
print(y_data_input)
for mov in y_data_input:
    if mov.any()==1:
        print('yey')

0.2035225048923679
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
yey
yey
yey
yey
yey
yey
yey


In [23]:
timesteps = X_input.shape[1]
data_dim = X_input.shape[2]

X_train = X_input[:4,:timesteps, :]
Y_train = y_data_input[:4, :timesteps]

X_test = X_input[4:, :timesteps, :]
Y_test = y_data_input[4:, :timesteps]

print(X_test.shape, X_train.shape, Y_train.shape, Y_test.shape)

(3, 212, 4096) (4, 212, 4096) (4, 212) (3, 212)


In [24]:
# constructing a many-to-one LSTM model in keras 
model = Sequential()

# normalization
model.add(BatchNormalization(input_shape=(timesteps, data_dim)))

model.add(LSTM(timesteps, return_sequences=True))
#input_shape=(timesteps, data_dim)

model.add(Flatten()) 
# add the final dense layer and then softmax
model.add(Dense(timesteps, activation='sigmoid'))
# going to add a softmax activation to this
#model.add(Activation('softmax'))

In [25]:
# a new metric of evaluation! the F-score!
def FScore2(y_true, y_pred):
    '''
    The F score, beta=2
    '''
    B2 = K.variable(4)
    OnePlusB2 = K.variable(5)
    pred = K.round(y_pred)
    tp = K.sum(K.cast(K.less(K.abs(pred - K.clip(y_true, .5, 1.)), 0.01), 'float32'), -1)
    fp = K.sum(K.cast(K.greater(pred - y_true, 0.1), 'float32'), -1)
    fn = K.sum(K.cast(K.less(pred - y_true, -0.1), 'float32'), -1)

    f2 = OnePlusB2 * tp / (OnePlusB2 * tp + B2 * fn + fp)

    return K.mean(f2)

In [28]:
# compiling LSTM model
# note that Ng used an Adam optimizer and categorical cross-entropy loss
# but this is a binary classification problem so I think the parameters below should suffice
model.compile(loss='binary_crossentropy',
              optimizer='Adam',
              metrics=['binary_accuracy', FScore2])

In [29]:
# running the LSTM model
model.fit(X_train, Y_train, epochs = 20, batch_size = 128, validation_data=(X_test, Y_test))
print("finished training!")

Train on 4 samples, validate on 3 samples
Epoch 1/20
4/4 [==============================] - 5s 1s/step - loss: 7.8222e-06 - binary_accuracy: 1.0000 - FScore2: 1.0000 - val_loss: 1.4668 - val_binary_accuracy: 0.6808 - val_FScore2: 0.1595
Epoch 2/20
4/4 [==============================] - 4s 876ms/step - loss: 6.2094e-06 - binary_accuracy: 1.0000 - FScore2: 1.0000 - val_loss: 1.4748 - val_binary_accuracy: 0.6792 - val_FScore2: 0.1814
Epoch 3/20
4/4 [==============================] - 3s 869ms/step - loss: 4.7627e-06 - binary_accuracy: 1.0000 - FScore2: 1.0000 - val_loss: 1.4837 - val_binary_accuracy: 0.6777 - val_FScore2: 0.1811
Epoch 4/20
4/4 [==============================] - 3s 862ms/step - loss: 3.6398e-06 - binary_accuracy: 1.0000 - FScore2: 1.0000 - val_loss: 1.4930 - val_binary_accuracy: 0.6730 - val_FScore2: 0.1802
Epoch 5/20
4/4 [==============================] - 4s 883ms/step - loss: 2.8124e-06 - binary_accuracy: 1.0000 - FScore2: 1.0000 - val_loss: 1.5021 - val_binary_accuracy: 

In [32]:
model.evaluate(X_test, Y_test)

3/3 [==============================] - 2s 523ms/step


[1.604862093925476, 0.654088020324707, 0.19976860284805298]

In [11]:
model.save('./VGG16_norm_lstm')

In [29]:
# trying to view the model output
out = model.predict(X_train)

movie_index = 1

print("model prediction:")
print(out[movie_index])
print("target:")
print(Y_train[movie_index])

print("before 64:")
print(out[movie_index][63])
print("64:")
print(out[movie_index][65])

print("rounded")
print(np.round(out)[movie_index])

model prediction:
[1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00
 1.9221041e-28 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00
 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00
 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00
 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00
 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 2.1595651e-19
 1.0000000e+00 1.0000000e+00 2.3602658e-26 1.0000000e+00 1.0000000e+00
 4.4973351e-18 3.1209957e-32 1.9935814e-32 3.3743915e-34 1.0000000e+00
 1.0000000e+00 2.1284409e-12 1.6664713e-14 1.0000000e+00 1.0000000e+00
 1.0000000e+00 1.0000000e+00 1.7663178e-08 1.0000000e+00 1.0000000e+00
 1.0000000e+00 1.0000000e+00 2.7702462e-30 2.5049629e-30 1.0000000e+00
 2.6652263e-31 4.6479136e-31 2.5350656e-34 4.2515438e-35 4.0209436e-32
 1.0000000e+00 9.4842254e-15 1.0000000e+00 1.4375714e-11 1.0000000e+00
 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.